name       : libetpan
version    : '1.8'
release    : 2
source     :
    - https://github.com/dinhviethoa/libetpan/archive/1.8.tar.gz : 4e67a7b4abadcf3cc16fa16e1621a68e54d489dadfd9a7d1f960c172e953b6eb
license    : BSD-3-Clause
component  : programming
summary    : Provides a portable, efficient framework for different kinds of mail access
description: |
    Provides a portable, efficient framework for different kinds of mail access
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
