name       : libetpan
version    : 1.9.3
release    : 5
source     :
    - https://github.com/dinhviethoa/libetpan/archive/1.9.3.tar.gz : 591f97d5102f600e668502fe1dd5a341e910a840d8ea62e689a3a79d8bfbac87
license    : BSD-3-Clause
component  : programming.library
summary    : Provides a portable, efficient framework for different kinds of mail access
description: |
    Provides a portable, efficient framework for different kinds of mail access
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
