name       : libetpan
version    : 1.9.4
release    : 7
source     :
    - https://github.com/dinhviethoa/libetpan/archive/1.9.4.tar.gz : 82ec8ea11d239c9967dbd1717cac09c8330a558e025b3e4dc6a7594e80d13bb1
license    : BSD-3-Clause
component  : programming.library
summary    : Provides a portable, efficient framework for different kinds of mail access
description: |
    Provides a portable, efficient framework for different kinds of mail access
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %patch -p1 < $pkgfiles/dont-put-user-ldflags-into-libs.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
