name       : libetpan
version    : 1.7.2
release    : 1
source     :
    - https://github.com/dinhviethoa/libetpan/archive/1.7.2.tar.gz : 32797282a420f3174f4a679548e20fa2bb4acb404b827d62c2f44d3de4eb3120
license    : BSD-3-Clause
component  : programming 
summary    : Provides a portable, efficient framework for different kinds of mail access
description: |
    Provides a portable, efficient framework for different kinds of mail access
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
